title: Wild Words —É–∫—Ä–∞—ó–Ω—Å—å–∫–æ—é üá∫üá¶
description: –ü–µ—Ä–µ–∫–ª–∞–¥ —Å–∏—Å—Ç–µ–º–Ω–æ–≥–æ –¥–æ–≤—ñ–¥–∫–æ–≤–æ–≥–æ –¥–æ–∫—É–º–µ–Ω—Ç—É –¥–ª—è –≥—Ä–∏ The Wildsea –≤—ñ–¥ –≤–∏–¥–∞–≤–Ω–∏—Ü—Ç–≤–∞ –ö–£–†–ê
theme: just-the-docs
repository: MokeievEugene/wild-words-ua.github.io

color_scheme: wild

permalink: pretty

defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"

search_enabled: false

nav_enabled: true
nav_sort: case_sensitive
heading_anchors: true

aux_links:
  "GitHub —Ä–µ–ø–æ–∑–∏—Ç–æ—Ä—ñ–π":
    - "https://github.com/MokeievEugene/wild-words-ua.github.io"

back_to_top: true
back_to_top_text: "–ù–∞–≥–æ—Ä—É"

footer_content: 'Copyright 2025 –Ñ–≤–≥–µ–Ω –ú–æ–∫–µ—î–≤, –≤–∏–¥–∞–≤–Ω–∏—Ü—Ç–≤–æ –ö–£–†–ê'
